from __future__ import annotations

from .models import UiLanguage


ZH_HANS: dict[str, str] = {
    "Accounts": "账号",
    "Settings": "设置",
    "Accounts view tooltip": "查看当前账号、添加账号、切换 OAuth/API 账号并刷新额度。",
    "Sessions view tooltip": "浏览、搜索和整理当前目标的 Codex 会话记录。",
    "Settings view tooltip": "管理 Sandbox/Real 目标、同步、修复、还原点和路径。",
    "Settings load failed: {error}": "设置加载失败：{error}",
    "Open Sandbox Codex": "打开沙箱 Codex",
    "Open Real Codex": "打开真实 Codex",
    "Open Sandbox Codex tooltip": "以 Sandbox Codex Home 启动 Codex Desktop，用来验证切换和会话是否在沙箱里生效。",
    "Open Real Codex tooltip": "打开真实 Codex Desktop。真实环境会使用 C:\\Users\\KIALA\\.codex。",
    "Use ChatGPT Login": "使用 ChatGPT 登录",
    "Use ChatGPT Login tooltip": "启动 Codex 登录流程，把新的 ChatGPT/OAuth 账号导入本地账号仓。",
    "Add API Account": "添加 API 账号",
    "Add API Account tooltip": "添加 OpenAI-compatible API Key、Base URL 和可选模型，用于在 OAuth/API 间切换。",
    "Refresh Quota": "刷新额度",
    "Refresh Quota tooltip": "重新读取当前目标账号的额度；失败时会显示可诊断的错误。",
    "Open Vault": "打开账号仓",
    "Open Vault tooltip": "打开本地账号仓目录，里面保存已导入账号的运行文件和 metadata。",
    "Rollback": "回滚",
    "Rollback tooltip": "恢复当前目标最近一次自动还原点。Real Mode 下会要求强确认。",
    "Current Account": "当前账号",
    "ChatGPT Accounts": "ChatGPT 账号",
    "API Accounts": "API 账号",
    "The active Codex home does not match a saved vault account.": "当前 Codex home 未匹配本地账号仓中的账号。",
    "No saved accounts in this group.": "此分组没有已保存账号。",
    "Switch": "切换",
    "Switch Real": "真实切换",
    "Switch tooltip": "把 Sandbox 切到这个账号，只改 SandboxCodexHome，不会修改真实 .codex。",
    "Switch Real tooltip": "把真实 .codex 切到这个账号；会创建还原点并要求强确认。",
    "Rename...": "重命名...",
    "Rename account tooltip": "只修改本地账号仓里的显示名，不影响 Codex 登录状态。",
    "Remove...": "删除...",
    "Remove account tooltip": "从本地账号仓移除这个保存的账号，不会主动删除真实 .codex。",
    "Active": "当前",
    "Saved": "已保存",
    "ChatGPT": "ChatGPT",
    "API key": "API 密钥",
    "local vault": "本地账号仓",
    "account preference": "账号偏好配置",
    "OAuth common": "OAuth 公共配置",
    "legacy account config": "旧账号配置",
    "remaining": "剩余",
    "Quota": "额度",
    "Quota: loading...": "额度：加载中...",
    "Quota: refresh queued...": "额度：已排队刷新...",
    "Quota refresh is already running; queued one fresh refresh.": "额度正在刷新；已排队一次强制刷新。",
    "Quota: refreshing...": "额度：刷新中...",
    "Quota: switching to {name}...": "额度：正在切换到 {name}...",
    "Quota refresh failed: {error}": "额度刷新失败：{error}",
    "Quota refreshed at {time}.": "额度已于 {time} 刷新。",
    "Quota unavailable": "额度不可用",
    "Target Mode": "目标模式",
    "Sandbox": "沙箱环境",
    "Real": "真实环境",
    "Sandbox target tooltip": "默认安全模式。切换、修复和回滚都作用于 SandboxCodexHome。",
    "Real target tooltip": "真实模式。后续写入会作用于真实 .codex，关键操作会要求强确认。",
    "Sessions target tooltip": "切换 Sessions Manager 浏览的 Codex Home 目标。",
    "Active target: {target}": "当前目标：{target}",
    "{target} Mode is active.": "{target} 模式已启用。",
    "Real Mode modifies {path} after confirmation.": "Real Mode 会在确认后修改 {path}。",
    "Maintenance": "维护",
    "Seed Sandbox": "种子化沙箱",
    "Seed Sandbox tooltip": "从真实 .codex 复制账号状态、会话、state 数据库和共享资产到 Sandbox，作为安全起点。",
    "Sync Sandbox to Real": "同步沙箱到真实环境",
    "Sync Sandbox to Real tooltip": "把勾选的 Sandbox 会话/资产同步回真实 .codex；写入前会创建 Real 还原点。",
    "Sync Sandbox Sessions to Real": "同步沙箱会话到真实环境",
    "Sync Sessions": "同步会话",
    "Sync Sessions tooltip": "同步 sessions、archived_sessions、session_index.jsonl，并更新 state_5.sqlite 线程元数据。",
    "Sessions rescan tooltip": "重新扫描当前目标的 sessions / archived_sessions，并更新会话索引。",
    "Sessions status filter tooltip": "按会话状态筛选当前列表。",
    "Sessions locate selected tooltip": "定位到当前打开的会话；如果父级文件夹已折叠，会自动展开。",
    "Sessions search popup tooltip": "打开会话搜索。",
    "Only User": "仅 User",
    "Only Assistant": "仅 Assistant",
    "Show only {kind} bubbles": "仅显示 {kind} 气泡",
    "Search": "搜索",
    "Scroll to top": "回到顶部",
    "Scroll to bottom": "回到底部",
    "Sync Assets": "同步资产",
    "Sync Assets tooltip": "同步 skills、prompts、agents、templates 等共享资产；不会复制 auth.json 或 config.toml。",
    "Choose at least one sync option.": "请至少选择一个同步选项。",
    "Sync progress: scanning Sandbox and Real {sections} for preview...": "同步进度：正在扫描沙箱和真实环境的 {sections} 以生成预览...",
    "Sync progress: preparing Sandbox {sections} to Real sync...": "同步进度：正在准备将沙箱 {sections} 同步到真实环境...",
    "sessions/assets": "会话/资产",
    "sessions": "会话",
    "assets": "资产",
    "nothing": "无内容",
    "Open Session Manager": "打开会话管理器",
    "Repair {target} Threads": "修复 {target} 对话",
    "Repair Threads tooltip": "修复当前目标的会话可见性，把 session JSONL 和 state_5.sqlite 的 provider 元数据对齐。",
    "Restore Points": "还原点",
    "Kind": "类型",
    "ID": "ID",
    "Created At": "创建时间",
    "Target": "目标",
    "Size": "大小",
    "Files": "文件数",
    "Note": "备注",
    "Loading snapshots...": "正在加载还原点...",
    "Loading restore points...": "正在加载还原点...",
    "Latest automatic: {latest} | automatic {auto_count}/50, {auto_size} | manual {manual_count}/50, {manual_size}": "最新自动还原点：{latest} | 自动 {auto_count}/50，{auto_size} | 手动 {manual_count}/50，{manual_size}",
    "none": "无",
    "Snapshot": "快照",
    "automatic": "自动",
    "manual": "手动",
    "Create Snapshot": "创建快照",
    "Create Snapshot tooltip": "手动创建当前还原点目标的完整快照，便于之后恢复。",
    "Restore Selected": "恢复所选",
    "Restore Selected tooltip": "恢复表格中选中的还原点。Real 目标恢复前会要求强确认。",
    "Rollback Last Automatic Change": "回滚最近自动更改",
    "Rollback Last Automatic Change tooltip": "恢复最近一次自动快照，适合撤销刚刚的 switch/sync/repair。",
    "Delete Selected": "删除所选",
    "Delete Selected tooltip": "删除表格中选中的还原点记录和备份文件。",
    "Open Snapshot Folder tooltip": "打开当前还原点目标的备份目录。",
    "Open Snapshot Folder": "打开快照文件夹",
    "Audit": "审计",
    "Time": "时间",
    "Event": "事件",
    "Status": "状态",
    "Summary": "摘要",
    "Loading recent audit events...": "正在加载最近审计事件...",
    "Open Logs": "打开日志",
    "Open Logs tooltip": "打开应用日志目录，用于查看后台任务、审计和错误信息。",
    "Paths": "路径",
    "App data": "应用数据",
    "Storage root": "存储根目录",
    "Sandbox home": "沙箱 home",
    "Real Codex home": "真实 Codex home",
    "Session Manager home": "Session Manager home",
    "Real Session Manager home": "真实 Session Manager home",
    "Snapshot folder": "快照文件夹",
    "Audit log": "审计日志",
    "OAuth common config": "OAuth 公共配置",
    "Details": "详情",
    "Switch language": "切换语言",
    "Switch language tooltip": "切换界面语言。不会影响账号、Sandbox 或 Real 数据。",
    "Details tooltip": "展开当前状态消息的完整输出，常用于查看后台任务错误。",
    "Status notification tooltip": "通知会自动消失；右侧 ✕ 按钮可立即清除。▾ 按钮负责展开完整输出。",
    "Dismiss tooltip": "关闭这条通知。",
    "English": "English",
    "Simplified Chinese": "简体中文",
    "Language changed.": "语言已切换。",
    "Add API Account Title": "添加 API 账号",
    "Display name": "显示名称",
    "Display name (optional)": "显示名称（可选）",
    "Base URL": "Base URL",
    "Model": "模型",
    "Model (optional)": "模型（可选）",
    "API key placeholder": "API 密钥",
    "API key and Base URL are required.": "API 密钥和 Base URL 不能为空。",
    "Validating API account...": "正在验证 API 账号...",
    "Starting Codex login. Complete the browser/device flow when it appears.": "正在启动 Codex 登录。请在浏览器或设备授权流程出现后完成登录。",
    "Switch progress: preparing {target} switch to {name}...": "切换进度：正在准备将 {target} 切换到 {name}...",
    "Add": "添加",
    "Rename Account": "重命名账号",
    "Rename": "重命名",
    "Display name is required.": "显示名称不能为空。",
    "Remove Account": "删除账号",
    "Remove {name} from the local vault? This does not modify the active Codex home.": "从本地账号仓删除 {name}？这不会修改当前 Codex home。",
    "Cancelled.": "已取消。",
    "Create a manual snapshot for {target}.": "为 {target} 创建手动快照。",
    "Manual snapshot": "手动快照",
    "Create": "创建",
    "Restore Snapshot": "恢复快照",
    "Select a snapshot first.": "请先选择一个快照。",
    "Delete Snapshot": "删除快照",
    "Delete {target} snapshot {snapshot_id}? This cannot be undone.": "删除 {target} 快照 {snapshot_id}？此操作不可撤销。",
}


def translate(language: UiLanguage, key: str) -> str:
    if language == UiLanguage.CHINESE:
        return ZH_HANS.get(key, key)
    return key
